"""Verisure Italy API client."""

from .client import VerisureClient, generate_device_id, generate_uuid
from .exceptions import (
    APIConnectionError,
    APIResponseError,
    AuthenticationError,
    OperationFailedError,
    OperationTimeoutError,
    SessionExpiredError,
    TwoFactorRequiredError,
    UnexpectedStateError,
    VerisureError,
    WAFBlockedError,
)
from .models import (
    PROTO_TO_STATE,
    STATE_TO_COMMAND,
    STATE_TO_PROTO,
    AlarmState,
    ArmCommand,
    ArmPanelResponse,
    ArmResult,
    CheckAlarmResponse,
    DisarmPanelResponse,
    DisarmResult,
    GeneralStatus,
    Installation,
    InteriorMode,
    LoginResponse,
    OperationResult,
    OtpPhone,
    PerimeterMode,
    ProtoCode,
    Service,
    parse_proto_code,
)

__all__ = [
    "PROTO_TO_STATE",
    "STATE_TO_COMMAND",
    "STATE_TO_PROTO",
    "APIConnectionError",
    "APIResponseError",
    "AlarmState",
    "ArmCommand",
    "ArmPanelResponse",
    "ArmResult",
    "AuthenticationError",
    "CheckAlarmResponse",
    "DisarmPanelResponse",
    "DisarmResult",
    "GeneralStatus",
    "Installation",
    "InteriorMode",
    "LoginResponse",
    "OperationFailedError",
    "OperationResult",
    "OperationTimeoutError",
    "OtpPhone",
    "PerimeterMode",
    "ProtoCode",
    "Service",
    "SessionExpiredError",
    "TwoFactorRequiredError",
    "UnexpectedStateError",
    "VerisureClient",
    "VerisureError",
    "WAFBlockedError",
    "generate_device_id",
    "generate_uuid",
    "parse_proto_code",
]
