"""Verisure Italy API client."""

__version__ = "0.8.3"

from .client import VerisureClient, generate_device_id, generate_uuid
from .exceptions import (
    APIConnectionError,
    APIResponseError,
    ArmingExceptionError,
    AuthenticationError,
    ImageCaptureError,
    OperationFailedError,
    OperationTimeoutError,
    SessionExpiredError,
    TwoFactorRequiredError,
    UnexpectedStateError,
    UnsupportedPanelError,
    VerisureError,
    WAFBlockedError,
)
from .models import (
    CAMERA_DEVICE_TYPES,
    PANEL_FAMILIES,
    PROTO_TO_STATE,
    STATE_TO_COMMAND,
    STATE_TO_PROTO,
    SUPPORTED_PANELS,
    AlarmState,
    ArmCommand,
    ArmResult,
    CameraDevice,
    CheckAlarmResponse,
    DisarmPanelResponse,
    DisarmResult,
    GeneralStatus,
    Installation,
    InteriorMode,
    LoginResponse,
    OperationResult,
    OtpPhone,
    PanelFamily,
    PerimeterMode,
    ProtoCode,
    RawDevice,
    Service,
    ServiceAttribute,
    Thumbnail,
    ZoneException,
    parse_proto_code,
)
from .probe import run_probe

__all__ = [
    "CAMERA_DEVICE_TYPES",
    "PANEL_FAMILIES",
    "PROTO_TO_STATE",
    "STATE_TO_COMMAND",
    "STATE_TO_PROTO",
    "SUPPORTED_PANELS",
    "APIConnectionError",
    "APIResponseError",
    "AlarmState",
    "ArmCommand",
    "ArmResult",
    "ArmingExceptionError",
    "AuthenticationError",
    "CameraDevice",
    "CheckAlarmResponse",
    "DisarmPanelResponse",
    "DisarmResult",
    "GeneralStatus",
    "ImageCaptureError",
    "Installation",
    "InteriorMode",
    "LoginResponse",
    "OperationFailedError",
    "OperationResult",
    "OperationTimeoutError",
    "OtpPhone",
    "PanelFamily",
    "PerimeterMode",
    "ProtoCode",
    "RawDevice",
    "Service",
    "ServiceAttribute",
    "SessionExpiredError",
    "Thumbnail",
    "TwoFactorRequiredError",
    "UnexpectedStateError",
    "UnsupportedPanelError",
    "VerisureClient",
    "VerisureError",
    "WAFBlockedError",
    "ZoneException",
    "generate_device_id",
    "generate_uuid",
    "parse_proto_code",
    "run_probe",
]
